export const rows = [
  {
    event: 'Purchase',
    date: '06/17/2020 at 7:13 PM PDT',
    price: '$120.00',
    email: 'demo@gmail.com',
    role: 'Advocate',
    friend_email: 'fr57483948@gmail.com',
    friend_role: 'Friend',
    status: 'Pending',
    status_detail: 'Passed fraud checks',
  },
  {
    event: 'Purchase',
    date: '07/10/2020 at 4:05 AM PDT',
    price: '$100.00',
    email: 'demo@gmail.com',
    role: 'Advocate',
    friend_email: 'fr57483948@gmail.com',
    friend_role: 'Friend',
    status: 'Flagged',
    status_detail: 'Marked as fraud',
  },
  {
    event: 'Purchase',
    date: '06/09/2020 at 12:42 PM PDT',
    price: '$28.00',
    email: 'demoefjefjoe@gmail.com',
    role: 'Advocate',
    friend_email: 'fr57483948@gmail.com',
    friend_role: 'Friend',
    status: 'Approved',
    status_detail: 'Passed fraud checks',
  },
  {
    event: 'Purchase',
    date: '08/17/2020 at 4:20 AM PDT',
    price: '$100.00',
    email: 'demowkwk@gmail.com',
    role: 'Advocate',
    friend_email: 'fr57483948@gmail.com',
    friend_role: 'Friend',
    status: 'Blocked',
    status_detail: 'Marked as fraud',
  },
  {
    event: 'Purchase',
    date: '06/09/2020 at 2:08 AM PDT',
    price: '$100.00',
    email: 'demo128302037202@gmail.com',
    role: 'Advocate',
    friend_email: 'fr57483948@gmail.com',
    friend_role: 'Friend',
    status: 'Voided',
    status_detail: 'Marked as fraud',
  },
];

export const header = [
  'Refferal event',
  'Advocate',
  'Friend',
  'Refferal status',
];
